-- File auto generated by purescript-bridge! --
module Agora.Effect.GovernorMutation where

import Agora.Governor (GovernorDatum)
import Ctl.Internal.Types.Transaction (TransactionInput)
import Data.Generic.Rep (class Generic)
import Data.Lens (Iso')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Newtype (class Newtype)

newtype MutateGovernorDatum = MutateGovernorDatum
  { governorRef :: TransactionInput
  , newDatum :: GovernorDatum
  }

derive instance Generic MutateGovernorDatum _

derive instance Newtype MutateGovernorDatum _

--------------------------------------------------------------------------------

_MutateGovernorDatum
  :: Iso' MutateGovernorDatum
       { governorRef :: TransactionInput, newDatum :: GovernorDatum }
_MutateGovernorDatum = _Newtype
