-- File auto generated by purescript-bridge! --
module Agora.Effect.GovernorMutation where

import Prelude

import Agora.Governor (GovernorDatum)
import Contract.PlutusData (class FromData, class ToData)
import Ctl.Extra.FieldOrder (class FieldOrder)
import Ctl.Extra.IsData (productFromData, productToData)
import Data.Generic.Rep (class Generic)
import Data.Lens (Iso')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Newtype (class Newtype)
import Prim.RowList (Cons, Nil)

newtype MutateGovernorDatum = MutateGovernorDatum
  { oldDatum :: GovernorDatum
  , newDatum :: GovernorDatum
  }

derive instance Generic MutateGovernorDatum _

derive instance Newtype MutateGovernorDatum _

derive newtype instance Show MutateGovernorDatum

instance
  FieldOrder MutateGovernorDatum
    ( Cons "oldDatum" GovernorDatum
        ( Cons "newDatum" GovernorDatum Nil
        )
    )

instance ToData MutateGovernorDatum where
  toData = productToData

instance FromData MutateGovernorDatum where
  fromData = productFromData

--------------------------------------------------------------------------------

_MutateGovernorDatum
  :: Iso' MutateGovernorDatum
       { oldDatum :: GovernorDatum, newDatum :: GovernorDatum }
_MutateGovernorDatum = _Newtype
