-- File auto generated by purescript-bridge! --
module Agora.Effect.GovernorMutation where

import Prelude

import Agora.Governor (GovernorDatum)
import Ctl.Internal.Types.Transaction (TransactionInput)
import Data.Generic.Rep (class Generic)
import Data.Lens (Iso')
import Data.Lens.Iso.Newtype (_Newtype)
import Data.Newtype (class Newtype)
import Ctl.Extra.FieldOrder (class FieldOrder)
import Prim.RowList (Cons, Nil)
import Ctl.Extra.IsData (productFromData, productToData)
import Contract.PlutusData (class FromData, class ToData)

newtype MutateGovernorDatum = MutateGovernorDatum
  { governorRef :: TransactionInput
  , newDatum :: GovernorDatum
  }

derive instance Generic MutateGovernorDatum _

derive instance Newtype MutateGovernorDatum _

derive newtype instance Show MutateGovernorDatum

instance
  FieldOrder MutateGovernorDatum
    ( Cons "governorRef" TransactionInput
        ( Cons "newDatum" GovernorDatum Nil
        )
    )

instance ToData MutateGovernorDatum where
  toData = productToData

instance FromData MutateGovernorDatum where
  fromData = productFromData

--------------------------------------------------------------------------------

_MutateGovernorDatum
  :: Iso' MutateGovernorDatum
       { governorRef :: TransactionInput, newDatum :: GovernorDatum }
_MutateGovernorDatum = _Newtype
